listen: "0.0.0.0:1080"
db_path: "gopanel.db"
collect_interval: "5s"
jwt_secret: "change-this-to-random-string"
username: "admin"
password: "admin"
alert:
  cpu: 90
  memory: 90
  disk: 90
  webhook: ""
